language: node_js
node_js:
  - '8'
  - '10'
  - '12'

before_script:
 - npm run lint
 - npm run build

jobs:
  include:
    - stage: test
      script: npm test && npm run coveralls
    - stage: deploy
      name: 'Semantic Release'
      node_js: '10'
      script: npm run semantic-release
