language: node_js
node_js:
  - '6'
  - '8'
  - '10'

before_script:
 - npm run lint
 - npm run build

jobs:
  include:
    - stage: test
      name: 'Tests'
      script: npm test
    - stage: coverage
      name: 'Code Coverage'
      script: npm run coveralls
    - stage: deploy
      name: 'Semantic Release'
      node_js: '10'
      script: npm run semantic-release
