language: node_js
node_js:
  - '6'
  - '8'
  - '10'

before_script:
 - npm run lint
 - npm run build

jobs:
  include:
    stage: test
    script: npm test
    stage: coverage
    script: script: npm run coveralls
    stage: deploy
    script: npm run semantic-release
