name: Release

on:
  push:
    branches:
      - 'main'
      - 'beta'
  pull_request:
    branches:
      - 'main'
      - 'beta'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Build Project
        run: pnpm build
      - name: Run Tests
        run: pnpm test

  release:
    name: Release
    needs: test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Check for pre release file
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".changeset/pre.json"
      - name: Remove Publish Tag
        if: ${{ github.github.ref_name == 'main' && steps.check_files.outputs.files_exists == 'true' }}
        run: pnpm changeset pre exit
      - name: Set Publish Tag
        if: ${{ github.github.ref_name != 'main' && steps.check_files.outputs.files_exists == 'false' }}
        run: pnpm changeset pre enter $HIJACKER_PRE_TAG
        env:
          HIJACKER_PRE_TAG: ${{ github.ref_name }}
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
          commit: Bump package versions
          title: Bump package versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}