name: CI/CD

# Run on push to all branches. But only PRs to main
on:
  push:
    branches:
      - 'monorepo'
      - 'beta'
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test
      # - name: Run Linting
      #   run: pnpm lint
      - name: Build Project
        run: pnpm build
      # - name: Coveralls Parallel
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     flag-name: run-${{ matrix.test_number }}
      #     path-to-lcov: './coverage/lcov.info'
      #     parallel: true

  # coveralls:
  #   name: Coveralls
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Coveralls Finished
  #       uses: coverallsapp/github-action@master
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         path-to-lcov: './coverage/lcov.info'
  #         parallel-finished: true

  # release:
  #   name: Release
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.x
  #     - name: Install Dependencies
  #       run: npm i
  #     - name: Build Project
  #       run: npm run build
  #     - name: Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: npm run semantic-release