name: Release

on:
  push:
    branches:
      - 'main'
      - 'beta'
  pull_request:
    branches:
      - 'main'
      - 'beta'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Lint Project
        run: pnpm lint
      - name: Build Project
        run: pnpm build
      - name: Run Tests
        run: pnpm test
      - name: 'Coveralls - @hijacker/core'
        if: ${{ matrix.node-version == '20.x' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: '@hijakcer/core'
          base-path: './packages/core'
          path-to-lcov: './packages/core/coverage/lcov.info'
          parallel: true
      - name: 'Coveralls - @hijacker/plugin-frontend'
        if: ${{ matrix.node-version == '20.x' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: '@hijakcer/plugin-frontend'
          base-path: './packages/plugin-frontend'
          path-to-lcov: './packages/plugin-frontend/coverage/lcov.info'
          parallel: true
      - name: 'Coveralls - @hijacker/plugin-graphql'
        if: ${{ matrix.node-version == '20.x' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: '@hijakcer/plugin-graphql'
          base-path: './packages/plugin-graphql'
          path-to-lcov: './packages/plugin-graphql/coverage/lcov.info'
          parallel: true

  finish:
    needs: Coveralls Finish
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true

  release:
    name: Release
    needs: test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Check for pre release file
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".changeset/pre.json"
      - name: Remove Publish Tag
        if: ${{ github.ref_name == 'main' && steps.check_files.outputs.files_exists == 'true' }}
        run: pnpm changeset pre exit
      - name: Set Publish Tag
        if: ${{ github.ref_name != 'main' && steps.check_files.outputs.files_exists == 'false' }}
        run: pnpm changeset pre enter $HIJACKER_PRE_TAG
        env:
          HIJACKER_PRE_TAG: ${{ github.ref_name }}
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish --tag $HIJACKER_RELEASE_TAG --no-git-checks
          commit: Bump package versions
          title: Bump package versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HIJACKER_RELEASE_TAG: ${{ github.ref_name == 'main' && 'main' || github.ref_name }}