name: Testing and Release

on:
  # Run on push to any branch
  push:
    branches:
      - '*'

  # Only run on PRs to master
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Run Litning
        run: npm run lint
      - name: Run Tests
        run: npm test

  release:
    needs: test
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Release
        run: npm run semantic-release -- --dryRun